### PR TITLE
User defined categories

### LINKED ISSUE #122: User defined Categories

### PR DESCRIPTION
**Pull request by joshuanianji**
Closes #122

### CODE REVIEW

**Comment by joshuanianji** [comment]
Currently, this PR is blocked because I need to figure out how to change the EditRecipe UI to enable category editing (we need more space!)

**Comment by LeCitrus** [comment]
LGTM

**Comment by joshuanianji** [comment]
Not ready to merge!

**Review by LeCitrus — APPROVED** [review]
LGTM

**Pull request merged**
