### PR TITLE
Recipe stuff

### PR DESCRIPTION
**Pull request by LeCitrus**

### CODE REVIEW

**Comment by LeCitrus** [comment]
Basic functionality is completed for recipes

**Comment by joshuanianji** [comment]
Looks like `IngredientStorageActivityTest` is failing again, let me check

**Comment by LeCitrus** [comment]
That's pretty quirky, I reran it and now it works

**Review by joshuanianji — APPROVED** [review]
LGTM!

**Comment by joshuanianji** [comment]
Indeed that is quirky

**Pull request merged**
