### PR TITLE
Changes for sorting

### PR DESCRIPTION
**Pull request by vedudx**

### CODE REVIEW

**Comment by joshuanianji** [comment]
Awesome, thanks @vedudx! Before I review, can you fix the merge conflicts!

**Review by joshuanianji — COMMENTED** [review]
These look good to me

**Comment by joshuanianji** [comment]
Can we have the spinner display what the current sort is? Right now it doesn't show anything.



Screenshot 2022-11-02 at 11 42 25 PM

**Comment by kailashs2002** [comment]
Change the getBestBefore to take the dateFormat as an argument instead of fixing it as "dd MMMM yyyy" inside the function.

I'll merge it to avoid having to fix merge conflicts as we update main, but leave the branch up so you can fix it.

**Comment by kailashs2002** [comment]
Besides that, lgtm!

**Review by kailashs2002 — APPROVED** [review]

**Pull request merged**
