### PR TITLE
Camera Image, Char Limit and Task Refactor

### PR DESCRIPTION
**Pull request by LeCitrus**
- Add ability to add images from camera
- Adds char limit to addRecipe
- Refactor some code to use Tasks (better async chaining)

### CODE REVIEW

**Review by joshuanianji — APPROVED** [review]
Changes look good right now, just fixing merge conflicts LOL

**Review by kailashs2002 — APPROVED** [review]
LGTM

**Review by kailashs2002 — APPROVED** [review]
nice

**Pull request merged**
